name: app_captusiat
description: "Aplicación para la búsqueda de vehículos con orden de captura"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  action_slider: ^0.7.0
  animate_do: ^3.3.4
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  geolocator: ^13.0.1
  get: ^4.6.6
  lottie: ^3.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/EuclidCircularA/Euclid-Circular-A-Light.ttf
          weight: 200
        - asset: assets/fonts/EuclidCircularA/Euclid-Circular-A-Regular.ttf
          weight: 400
        - asset: assets/fonts/EuclidCircularA/Euclid-Circular-A-Medium.ttf
          weight: 500
        - asset: assets/fonts/EuclidCircularA/Euclid-Circular-A-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EuclidCircularA/Euclid-Circular-A-Bold.ttf
          weight: 700
